from __future__ import annotations

import arcade

from autochess.models import MatchState
from autochess.views.game_view import GameView


class BuildView(arcade.View):
    def __init__(self, match_state: MatchState):
        super().__init__()
        self.match_state = match_state

    def on_draw(self) -> None:
        self.clear((30, 24, 20))
        arcade.Text(
            "Build Phase",
            self.window.width / 2,
            self.window.height - 90,
            arcade.color.LIGHT_CYAN,
            30,
            anchor_x="center",
        ).draw()
        arcade.Text(
            "Player build is currently generated by config rules.",
            self.window.width / 2,
            self.window.height / 2,
            arcade.color.LIGHT_GRAY,
            16,
            anchor_x="center",
        ).draw()
        arcade.Text(
            "Press ENTER to continue to rounds.",
            self.window.width / 2,
            self.window.height / 2 - 40,
            arcade.color.WHITE_SMOKE,
            14,
            anchor_x="center",
        ).draw()

    def on_key_press(self, symbol: int, modifiers: int) -> None:
        if symbol == arcade.key.ENTER:
            self.window.show_view(GameView(self.match_state))
